#!/usr/bin/env bash
# Generates the bundled skin-texture presets under
# apps/web/public/textures/skin/. Fully scripted (no manual image-editor
# steps), reproducible, requires only ImageMagick (`magick` on PATH).
#
# These are original procedural artwork — not sourced from any external
# asset pack — generated by layering:
#   1. a flat base tone (fair/medium/deep)
#   2. a low-frequency "mottle" layer (blurred plasma noise, blended at low
#      opacity) for organic blotchy tonal variation
#   3. a high-frequency "pore" layer (blurred Gaussian noise, blended at low
#      opacity) for fine skin grain
# composited with the `Overlay` blend mode, which leaves a mid-gray (128)
# blend layer a no-op and scales lighter/darker deviations proportionally —
# unlike `Multiply`/`HardLight`, this doesn't blow out to solid black/white.
#
# Since these are entirely own-work procedural output (no vendored assets,
# no external files), there is no license/attribution to track — see
# apps/web/public/textures/skin/SOURCES.md.
set -euo pipefail

OUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/apps/web/public/textures/skin"
mkdir -p "$OUT_DIR"

SIZE=1024
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Medium-frequency mottling from blurred Gaussian noise (~8 px blotches at
# 1024). The body mesh's UV layout splits into islands (torso/arms/hands/
# head); statistically uniform small-scale noise keeps every island at the
# same average tone, so limbs can't render visibly lighter or darker than
# the torso the way low-frequency plasma blotches did.
gen_mottle() {
  local seed="$1" out="$2"
  magick -size ${SIZE}x${SIZE} -seed "$seed" xc:gray -attenuate 1.2 +noise Gaussian -colorspace Gray -blur 0x4 -auto-level -depth 8 "$TMP/mottle_raw_$seed.png"
  magick -size ${SIZE}x${SIZE} xc:gray "$TMP/mottle_raw_$seed.png" -compose Blend -define compose:args=24 -composite -depth 8 "$out"
}

# High-frequency fine grain (pores), independent of tone.
gen_pores() {
  local out="$1"
  magick -size ${SIZE}x${SIZE} xc:gray -attenuate 0.9 +noise Gaussian -colorspace Gray -depth 8 "$TMP/pore_raw.png"
  magick -size ${SIZE}x${SIZE} xc:gray "$TMP/pore_raw.png" -compose Blend -define compose:args=22 -composite -depth 8 "$out"
}

gen_pores "$TMP/pores.png"

gen_skin() {
  local name="$1" color="$2" seed="$3"
  gen_mottle "$seed" "$TMP/mottle_$name.png"
  magick -size ${SIZE}x${SIZE} "xc:$color" \
    "$TMP/mottle_$name.png" -compose Overlay -composite \
    "$TMP/pores.png" -compose Overlay -composite \
    -depth 8 -strip -define png:compression-level=9 \
    "$OUT_DIR/$name.png"
  echo "wrote $OUT_DIR/$name.png ($(du -h "$OUT_DIR/$name.png" | cut -f1))"
}

gen_skin fair   '#e0b48c' 1
gen_skin medium '#c68863' 2
gen_skin deep   '#8b5a3c' 3
